name: Deploy to Docker Hub

on:
  push:
    branches:
      - master
    if: "!contains(github.event.head_commit.message, 'Merge pull request')"
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Setup Docker Compose
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: docker-compose.yaml
          compose-command: build

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          tags: ${{ secrets.DOCKER_USERNAME }}/libdocker:latest
          image: oyepuru/libdocker:latest
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
